# Generated by Django 4.0.1 on 2022-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoodiesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('download_link', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('product_link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dzhempery_i_svitery',
            },
        ),
    ]
