# Generated by Django 4.0.1 on 2022-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersuggested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersuggested',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usersuggested',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usersuggested',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
