# Generated by Django 4.0.1 on 2022-03-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_accessrecord_name_alter_webpage_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='instagramm_link',
        ),
    ]
